#!/usr/bin/env python3
"""Ensure ATS config is ready for 502/504 origin-timeout timeline testing.

This script targets an ATS root (e.g. /opt/ats) and supports:
1) Check readiness.
2) Apply test config:
   - Replace remap.config completely with a minimal test remap file.
   - Update records.yaml via YAML parsing.
3) Restore records.yaml / remap.config from backups.

Backup files are created as:
  <file>.bak-YYYYmmdd-HHMMSS

Usage examples:
  python3 ensure_ats_timeout_test_config.py --ats-root /opt/ats --check
  python3 ensure_ats_timeout_test_config.py --ats-root /opt/ats --apply
  python3 ensure_ats_timeout_test_config.py --ats-root /opt/ats --restore latest
  python3 ensure_ats_timeout_test_config.py --ats-root /opt/ats --restore 20260306-121923
  python3 ensure_ats_timeout_test_config.py --ats-root /opt/ats --list-backups
"""

from __future__ import annotations

import argparse
import datetime as dt
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, List, Sequence

import yaml


RECORDS_UPDATES: Dict[str, Any] = {
    "connect_attempts_timeout": 1,
    "connect_attempts_max_retries": 2,
    "connect_attempts_max_retries_down_server": 2,
    "transaction_no_activity_timeout_out": 1,
}

EXPECTED_REMAP_TEXT = """# Minimal remap config for 502/504 timeout timeline tests.
# Generated by ensure_ats_timeout_test_config.py.
map /__timeout502 https://127.0.0.1:19002/
map /__timeout504 http://127.0.0.1:19004/
map /__ok200_bt http://127.0.0.1:19010/
"""


def _backup(path: Path) -> Path:
    stamp = dt.datetime.now().strftime("%Y%m%d-%H%M%S")
    out = path.with_name(f"{path.name}.bak-{stamp}")
    shutil.copy2(path, out)
    return out


def _load_yaml(path: Path) -> Dict[str, Any]:
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    if data is None:
        data = {}
    if not isinstance(data, dict):
        raise RuntimeError(f"{path}: YAML top-level must be a mapping")
    return data


def _dump_yaml(path: Path, data: Dict[str, Any]) -> None:
    path.write_text(yaml.safe_dump(data, sort_keys=False), encoding="utf-8")


def _ensure_records_data(data: Dict[str, Any]) -> tuple[Dict[str, Any], List[str]]:
    out = dict(data)
    changes: List[str] = []

    records = out.get("records")
    if records is None:
        records = {}
        out["records"] = records
        changes.append("records.yaml: add 'records' mapping")
    if not isinstance(records, dict):
        raise RuntimeError("records.yaml: 'records' must be a mapping")

    http = records.get("http")
    if http is None:
        http = {}
        records["http"] = http
        changes.append("records.yaml: add 'records.http' mapping")
    if not isinstance(http, dict):
        raise RuntimeError("records.yaml: 'records.http' must be a mapping")

    for key, want in RECORDS_UPDATES.items():
        old = http.get(key, None)
        if old != want:
            http[key] = want
            if old is None:
                changes.append(f"records.yaml: add http.{key}={want}")
            else:
                changes.append(f"records.yaml: set http.{key}={want} (was {old})")

    return out, changes


def _normalize_lines(text: str) -> List[str]:
    return [ln.rstrip() for ln in text.splitlines()]


def _remap_ready(current_text: str) -> bool:
    return _normalize_lines(current_text) == _normalize_lines(EXPECTED_REMAP_TEXT)


def _find_backups(path: Path) -> List[Path]:
    pattern = f"{path.name}.bak-*"
    backups = [p for p in path.parent.glob(pattern) if p.is_file()]
    backups.sort(key=lambda p: p.name)
    return backups


def _resolve_backup(path: Path, choice: str) -> Path:
    backups = _find_backups(path)
    if not backups:
        raise RuntimeError(f"No backups found for {path}")

    if choice == "latest":
        return backups[-1]

    if Path(choice).is_file():
        return Path(choice)

    # Treat as timestamp suffix.
    suffix = f".bak-{choice}"
    matches = [b for b in backups if b.name.endswith(suffix)]
    if len(matches) == 1:
        return matches[0]
    if len(matches) > 1:
        raise RuntimeError(f"Ambiguous backup choice '{choice}' for {path}")

    raise RuntimeError(f"No backup matching '{choice}' for {path}")


def _restore_file(target: Path, choice: str) -> Path:
    src = _resolve_backup(target, choice)
    shutil.copy2(src, target)
    return src


def _print_backup_versions(records: Path, remap: Path) -> None:
    print(f"Backups for {records}:")
    rb = _find_backups(records)
    if not rb:
        print("- (none)")
    else:
        for p in rb:
            print(f"- {p.name}")

    print(f"\nBackups for {remap}:")
    mb = _find_backups(remap)
    if not mb:
        print("- (none)")
    else:
        for p in mb:
            print(f"- {p.name}")


def _check_mode(records_path: Path, remap_path: Path) -> int:
    data = _load_yaml(records_path)
    new_data, rec_changes = _ensure_records_data(data)

    remap_cur = remap_path.read_text(encoding="utf-8")
    remap_changes: List[str] = []
    if not _remap_ready(remap_cur):
        remap_changes.append("remap.config: differs from expected minimal test remap")

    changed_records = new_data != data
    changed_remap = bool(remap_changes)

    if changed_records or changed_remap:
        print("NOT READY: changes required")
        for c in rec_changes + remap_changes:
            print(f"- {c}")
        return 1

    print("READY: config already matches timeout test requirements")
    return 0


def _apply_mode(ats_root: Path, records_path: Path, remap_path: Path, backup: bool) -> int:
    data = _load_yaml(records_path)
    new_data, rec_changes = _ensure_records_data(data)

    remap_cur = remap_path.read_text(encoding="utf-8")
    changed_records = new_data != data
    changed_remap = not _remap_ready(remap_cur)

    if not (changed_records or changed_remap):
        print("NO CHANGES: config already ready")
        _reload_ats_config(ats_root)
        return 0

    if backup:
        if changed_records:
            b = _backup(records_path)
            print(f"backup: {b}")
        if changed_remap:
            b = _backup(remap_path)
            print(f"backup: {b}")

    if changed_records:
        _dump_yaml(records_path, new_data)
    if changed_remap:
        remap_path.write_text(EXPECTED_REMAP_TEXT, encoding="utf-8")

    print("APPLIED:")
    for c in rec_changes:
        print(f"- {c}")
    if changed_remap:
        print("- remap.config: replaced with expected minimal test remap")
    print(f"updated: {records_path if changed_records else '(records unchanged)'}")
    print(f"updated: {remap_path if changed_remap else '(remap unchanged)'}")
    _reload_ats_config(ats_root)
    return 0


def _restore_mode(ats_root: Path, records_path: Path, remap_path: Path, choice: str) -> int:
    restored = []
    skipped = []

    for target in (records_path, remap_path):
        try:
            src = _restore_file(target, choice)
            restored.append((target, src))
        except RuntimeError as e:
            skipped.append(f"{target}: {e}")

    if not restored:
        raise RuntimeError(
            "No files restored. " + "; ".join(skipped)
        )

    print("RESTORED:")
    for target, src in restored:
        print(f"- {target} <= {src}")
    if skipped:
        print("SKIPPED:")
        for msg in skipped:
            print(f"- {msg}")
    _reload_ats_config(ats_root)
    return 0


def _validate_paths(ts_dir: Path) -> tuple[Path, Path]:
    records = ts_dir / "records.yaml"
    remap = ts_dir / "remap.config"
    if not records.is_file() or not remap.is_file():
        raise RuntimeError(f"missing required config files under {ts_dir}")
    return records, remap


def _reload_ats_config(ats_root: Path) -> None:
    traffic_ctl = ats_root / "bin" / "traffic_ctl"
    if not traffic_ctl.is_file():
        raise RuntimeError(f"traffic_ctl not found at {traffic_ctl}")
    proc = subprocess.run(
        [str(traffic_ctl), "config", "reload"],
        check=False,
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        stderr = proc.stderr.strip()
        stdout = proc.stdout.strip()
        detail = stderr or stdout or f"exit={proc.returncode}"
        raise RuntimeError(f"config reload failed via {traffic_ctl}: {detail}")
    print("reloaded: ATS config via traffic_ctl config reload")


def main(argv: Sequence[str] | None = None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--ats-root", required=True, help="ATS root path (equivalent to /opt/ats)")
    mode = ap.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true", help="Check only; do not write changes")
    mode.add_argument("--apply", action="store_true", help="Apply test config in place")
    mode.add_argument(
        "--restore",
        metavar="VERSION",
        help="Restore from backups: 'latest', backup timestamp (e.g. 20260306-121923), or full backup path",
    )
    mode.add_argument("--list-backups", action="store_true", help="List available backup versions")
    ap.add_argument(
        "--no-backup",
        action="store_true",
        help="Do not create backups on --apply (default: create backups when changes are written)",
    )
    args = ap.parse_args(argv)

    root = Path(args.ats_root)
    ts_dir = root / "etc" / "trafficserver"
    try:
        records_path, remap_path = _validate_paths(ts_dir)
    except RuntimeError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 2

    try:
        if args.list_backups:
            _print_backup_versions(records_path, remap_path)
            return 0
        if args.check:
            return _check_mode(records_path, remap_path)
        if args.apply:
            return _apply_mode(root, records_path, remap_path, backup=not args.no_backup)
        if args.restore is not None:
            return _restore_mode(root, records_path, remap_path, args.restore)
    except Exception as e:  # pylint: disable=broad-except
        print(f"ERROR: {e}", file=sys.stderr)
        return 2

    return 2


if __name__ == "__main__":
    raise SystemExit(main())
